### ISSUE TITLE
出大问题了，抓取失败

### ISSUE THREAD

**Issue by xchnotxzh** [Uchiha-Peng/weibo2markdown#1]
有的账号会抓取失败。

`本次抓取成功....
本次抓取成功....
本次抓取成功....
本次抓取成功....
出大问题了，抓取失败   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Weibo.Program.getWeiboList(String userId) in D:\code\c#\weibo2markdown\Program.cs:line 214`

**Comment by Uchiha-Peng** [comment]
是正常账号，还是封号、或是注销等待期的账号呢。

**Comment by Uchiha-Peng** [comment]
我刚试了，没有问题啊，你不用编译源码，直接从 [Release](https://github.com/Uchiha-Peng/weibo2markdown/files/4941554/ExportWeibo2Md.V1.0.zip)下载，解压，运行可执行文件，输入微博ID就可以了，是微博ID，不是用户名。
![image](https://user-images.githubusercontent.com/20633089/92679169-4648be00-f35a-11ea-8c78-022a4c9a0c86.png)

**Comment by Uchiha-Peng** [comment]
你这个是插入数据库的时候出错了，不是抓取出错。请在VS中选中sqlite数据库文件——属性——始终复制

**Comment by yetanotherface** [comment]
谢谢回复，已经解决。
我的问题是通过dotnet run 源码 方式运行时出现的。
通过release版本直接运行没有这个问题。

**Comment by Uchiha-Peng** [comment]
> ，
> 释放中包括：中等
> 
> 问题一：
> `本次抓取成功.... 本次抓取成功.... 本次抓取成功.... 本次抓取成功.... 请求失败，第1次尝试中...... 请求失败，第2次尝试中...... 请求失败，第3次尝试中...... 出大问题了，抓取失败 at CallSite.Target(Closure , CallSite , Object ) at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) at CallSite.Target(Closure , CallSite , Object ) at Weibo.Program.getWeiboList(String userId) in D:\Csharp\weibo2markdown\Program.cs:line 197 导出失败........，点击任意键结束程序`
> 
> 2：
> 1 命令蝙蝠， I 关系连接连接
> ） 在微软. 实体框架工作核心. 存储. 关系数据库. 保存更改 （Ilist1 条
> 目到保存） 在微软. 实体帧工作核心. 更改跟踪. 内部. 状态经理. 保存更改 （DbContext _， 布尔接受微软
> 的全变成功. 实体框架核心. 存储. 内部. Noop 执行战略. 执行 [Tstate， 研究] （Tstate 状态， Func3 验证
> 成功） 在微软. 实体 帧工作核心. 更改跟踪. 内部. 国家经理. 保存更改 （布尔接受所有更改成功）
> 在微软. 实体框架工作核心. dbcontext. 保存更改 （布尔接受所有更改成功）
> 在微软. 实体框架核心. Dbcontext. 保存更改 （）
> 在微博. 程序. 得到韦博列表 （字符串用户 Id） 在 D：[Csharp] 微博标记下]程序.cs：
> 行 180 行文.，点击任意键结束程序'`本次抓取成功.... 本次抓取成功.... 出大问题了，抓取失败 at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection) at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable``1 entries) at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList``3 operation, Func`
> 
> 人， 威博伊德 ， - - 3304308205

小哥，问题已经解决，是微博接口相应参数有所变动。我已经重新写了一个版本，之前代码写的比较垃圾，这个会简洁明了很多，欢迎使用反馈，谢谢。
